### ISSUE TITLE
BUG: Generating Invalid CSS

### ISSUE THREAD

**Issue by selbyk** [nknapp/swagger-to-html#3]
So, I just noticed that running swagger-to-html is generating CSS with a tiiiiiny, tiiiiny bug.

I beautified the minified CSS and on line 3013 I found the culprit:

``` css
.radio input[type="radio"],.radio-inline input[type="radio"],.checkbox input[type="checkbox"],.checkbox-inline input[type="checkbox"] {
    position:absolute;
    margin-left:-20px;
    margin-top:4px \9
}
```

That '\9' definitely shouldn't be there lol.  Any ideas on how it's sneaking in there?
